name: Check that the code runs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_run:
    name: Check that tutorials run

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [3.11]
        day: [1, 2, 3]
      fail-fast: false

    steps:
    - run: |
        echo "Testing Day ${{ matrix.day }} Tutorials on python ${{ matrix.python-version }}"
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v6
      with:
        python-version: '3.11'
    - name: Installing requirements
      run: |
        pip install -r requirements.txt
    - name: Test notebooks execution
      run: |
        for file in Tutorials/Day_${{ matrix.day }}/*ipynb; do
            echo "Checking ${file}";
            if ! ./tests/check_run.sh "${file}"; then
                echo "::error file=${file},title=Error";
                exit 1;
            fi
        done
